import {
  FileEdit,
  BadgeCheck,
  UserPlus,
  Dumbbell,
  Star,
  CircleDollarSign,
  TrendingUp,
  Rocket,
  Medal,
  ShieldCheck,
  ThumbsUp,
  Sparkles,
  Gem,
  Award,
  Crown,
  Trophy,
  LucideIcon,
  HelpCircle,
  Footprints,
  Flame,
  Timer,
  MapPin,
  Map,
  Globe,
  Moon,
  Watch,
  Bluetooth,
} from "lucide-react";

// Map badge icon names stored in DB to actual Lucide components
export const BADGE_ICON_MAP: Record<string, LucideIcon> = {
  FileEdit,
  BadgeCheck,
  UserPlus,
  Dumbbell,
  Star,
  MessageSquareStar: Star,
  CircleDollarSign,
  TrendingUp,
  Rocket,
  Medal,
  ShieldCheck,
  ThumbsUp,
  Sparkles,
  Gem,
  Award,
  crown: Crown,
  Crown,
  Trophy,
  // Health badge icons (lowercase DB values)
  footprints: Footprints,
  Footprints,
  flame: Flame,
  Flame,
  timer: Timer,
  Timer,
  "map-pin": MapPin,
  MapPin,
  map: Map,
  Map,
  globe: Globe,
  Globe,
  moon: Moon,
  Moon,
  watch: Watch,
  Watch,
  bluetooth: Bluetooth,
  Bluetooth,
};

export function getBadgeIcon(iconName: string): LucideIcon {
  return BADGE_ICON_MAP[iconName] || HelpCircle;
}
