import { DocsLayout } from "@/components/docs/DocsLayout";
import { DocTip, DocStep, DocInfo, DocWarning } from "@/components/docs/DocComponents";
import { Brain, Dumbbell, Apple, Moon, Lightbulb, CheckCircle, XCircle, RefreshCw } from "lucide-react";

export default function AIPlanRecommendationsDocs() {
  return (
    <DocsLayout
      title="AI Plan Recommendations | FitConnect Coach Guide"
      description="Get AI suggestions for next training phases based on client progress. Proactive programme optimisation."
      breadcrumbs={[
        { label: "Coach Guide", href: "/docs/coach" },
        { label: "AI Tools", href: "/docs/coach/ai" },
        { label: "Plan Recommendations" },
      ]}
    >
      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">What Are AI Recommendations?</h2>
        <p>
          AI Plan Recommendations are proactive suggestions generated by analysing your client's 
          data. Instead of waiting for you to request help, the AI identifies opportunities 
          to improve their plan and surfaces actionable recommendations.
        </p>
        
        <p>
          Think of them as an AI assistant that reviews each client's progress and says, 
          "Based on what I'm seeing, you might want to consider this change."
        </p>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Recommendation Types</h2>
        
        <div className="grid md:grid-cols-2 gap-4 mt-4">
          <div className="p-4 border rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <Dumbbell className="h-5 w-5 text-blue-500" />
              <h3 className="font-medium">Workout Recommendations</h3>
            </div>
            <ul className="text-sm text-muted-foreground space-y-1">
              <li>Increase volume for lagging muscle groups</li>
              <li>Add progressive overload to stalled exercises</li>
              <li>Swap exercises for better muscle activation</li>
              <li>Adjust training frequency based on recovery</li>
            </ul>
          </div>
          
          <div className="p-4 border rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <Apple className="h-5 w-5 text-green-500" />
              <h3 className="font-medium">Nutrition Recommendations</h3>
            </div>
            <ul className="text-sm text-muted-foreground space-y-1">
              <li>Adjust calories based on weight trends</li>
              <li>Rebalance macros for goals</li>
              <li>Address micronutrient gaps</li>
              <li>Meal timing optimisation</li>
            </ul>
          </div>
          
          <div className="p-4 border rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <Moon className="h-5 w-5 text-purple-500" />
              <h3 className="font-medium">Recovery Recommendations</h3>
            </div>
            <ul className="text-sm text-muted-foreground space-y-1">
              <li>Add deload week based on fatigue signals</li>
              <li>Improve sleep habits</li>
              <li>Reduce training intensity after plateau</li>
              <li>Schedule active recovery sessions</li>
            </ul>
          </div>
          
          <div className="p-4 border rounded-lg">
            <div className="flex items-center gap-2 mb-2">
              <Lightbulb className="h-5 w-5 text-amber-500" />
              <h3 className="font-medium">General Recommendations</h3>
            </div>
            <ul className="text-sm text-muted-foreground space-y-1">
              <li>Update goals based on progress</li>
              <li>Connect wearable for better tracking</li>
              <li>Log measurements more frequently</li>
              <li>Schedule a check-in session</li>
            </ul>
          </div>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Priority Levels</h2>
        <p>Each recommendation is assigned a priority level:</p>
        
        <div className="space-y-3 mt-4">
          <div className="flex items-start gap-3 p-3 border rounded-lg border-red-500/30 bg-red-500/5">
            <span className="px-2 py-1 bg-red-500 text-white text-xs font-medium rounded">HIGH</span>
            <div>
              <p className="font-medium">Requires immediate attention</p>
              <p className="text-sm text-muted-foreground">
                Client is at risk of injury, significant regression, or plan failure. Address within 24-48 hours.
              </p>
            </div>
          </div>
          
          <div className="flex items-start gap-3 p-3 border rounded-lg border-amber-500/30 bg-amber-500/5">
            <span className="px-2 py-1 bg-amber-500 text-white text-xs font-medium rounded">MEDIUM</span>
            <div>
              <p className="font-medium">Should be addressed soon</p>
              <p className="text-sm text-muted-foreground">
                Will improve results if implemented. Review during your next planning session.
              </p>
            </div>
          </div>
          
          <div className="flex items-start gap-3 p-3 border rounded-lg border-blue-500/30 bg-blue-500/5">
            <span className="px-2 py-1 bg-blue-500 text-white text-xs font-medium rounded">LOW</span>
            <div>
              <p className="font-medium">Nice to have</p>
              <p className="text-sm text-muted-foreground">
                Optimisation opportunities. Consider when time allows or during plan reviews.
              </p>
            </div>
          </div>
        </div>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Data Used for Generation</h2>
        <p>The AI analyses multiple data points to generate relevant recommendations:</p>
        
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>Progress logs</strong> – Weight, measurements, body composition trends</li>
          <li><strong>Workout history</strong> – Completion rates, exercise performance, volume trends</li>
          <li><strong>Nutrition logs</strong> – Calorie and macro adherence, meal consistency</li>
          <li><strong>Wearable data</strong> – Steps, sleep, heart rate variability, recovery metrics</li>
          <li><strong>Engagement signals</strong> – Habit compliance, message responsiveness, session attendance</li>
          <li><strong>Goals and timelines</strong> – Current objectives and target dates</li>
        </ul>
        
        <DocInfo>
          More complete client data leads to better recommendations. Encourage clients to log 
          consistently and connect wearable devices.
        </DocInfo>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Applying Recommendations</h2>
        
        <DocStep stepNumber={1} title="Review the Recommendation">
          Read the suggestion and the rationale provided. The AI explains why it's making this 
          recommendation based on the client's data.
        </DocStep>
        
        <DocStep stepNumber={2} title="View Suggested Changes">
          Click <strong>View Details</strong> to see the specific changes the AI is proposing – 
          which exercises, foods, or settings would be modified.
        </DocStep>
        
        <DocStep stepNumber={3} title="Apply or Modify">
          Click <strong>Apply</strong> to implement the changes directly, or <strong>Edit</strong> 
          to make adjustments before applying.
        </DocStep>
        
        <DocStep stepNumber={4} title="Notify Client (Optional)">
          Choose whether to message the client about the change. The AI can draft an explanation 
          message for you.
        </DocStep>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Dismissing Recommendations</h2>
        <p>
          Not every recommendation will be relevant. You can dismiss suggestions that don't apply:
        </p>
        
        <div className="flex flex-wrap gap-4 mt-4">
          <div className="flex items-center gap-2 p-3 border rounded-lg">
            <XCircle className="h-5 w-5 text-muted-foreground" />
            <span className="text-sm">Not applicable</span>
          </div>
          <div className="flex items-center gap-2 p-3 border rounded-lg">
            <XCircle className="h-5 w-5 text-muted-foreground" />
            <span className="text-sm">Already addressed</span>
          </div>
          <div className="flex items-center gap-2 p-3 border rounded-lg">
            <XCircle className="h-5 w-5 text-muted-foreground" />
            <span className="text-sm">Client preference</span>
          </div>
          <div className="flex items-center gap-2 p-3 border rounded-lg">
            <XCircle className="h-5 w-5 text-muted-foreground" />
            <span className="text-sm">Will consider later</span>
          </div>
        </div>
        
        <DocTip>
          Dismissing recommendations helps the AI learn. It will adjust future suggestions 
          based on what you find useful.
        </DocTip>
      </section>

      <section className="space-y-4">
        <h2 className="text-2xl font-semibold">Regenerating Recommendations</h2>
        <p>
          You can request fresh recommendations at any time:
        </p>
        
        <ul className="list-disc pl-6 space-y-2">
          <li><strong>After applying changes</strong> – Get new suggestions based on the updated plan</li>
          <li><strong>After new data arrives</strong> – Refresh after client logs progress or syncs wearable</li>
          <li><strong>During planning sessions</strong> – Generate batch recommendations for multiple clients</li>
        </ul>
        
        <DocWarning>
          Recommendations are generated based on available data. If a client hasn't logged 
          anything recently, suggestions may be less accurate or unavailable.
        </DocWarning>
      </section>
    </DocsLayout>
  );
}
