import { createClient } from "@supabase/supabase-js";
import { corsHeaders, handleCors, jsonResponse, errorResponse } from "../_shared/cors.ts";

const BABYLOVEGROWTH_API_BASE = "https://api.babylovegrowth.ai/api/integrations/v1/articles";

// Only import 1 article per sync for daily drip-feed
const ARTICLES_PER_SYNC = 1;

function removeAttributionFooter(html: string): string {
  return html.replace(
    /<p>\s*<a[^>]*href="https?:\/\/(?:www\.)?babylovegrowth\.ai"[^>]*>Article generated by BabyLoveGrowth<\/a>\s*<\/p>/gi,
    ""
  );
}

interface BabyLoveGrowthListItem {
  id: number;
  title: string;
  metaDescription?: string;
  content_html?: string;
  languageCode?: string;
  publicUrl?: string;
  createdAt?: string;
  created_at?: string;
}

interface BabyLoveGrowthArticle {
  id: number;
  title: string;
  slug?: string;
  content_html?: string;
  content_markdown?: string;
  meta_description?: string;
  hero_image_url?: string;
  keywords?: string[];
  seedKeyword?: string;
  created_at?: string;
  orgWebsite?: string;
}

function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .trim();
}

function calculateReadingTime(html: string): number {
  if (!html) return 1;
  const text = html.replace(/<[^>]*>/g, "");
  const words = text.split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.ceil(words / 200));
}

function extractExcerpt(content: string, maxLength = 160): string {
  if (!content) return "";
  const text = content.replace(/<[^>]*>/g, "");
  if (text.length <= maxLength) return text;
  return text.substring(0, maxLength).trim() + "...";
}

async function fetchArticleById(id: number, apiKey: string): Promise<BabyLoveGrowthArticle | null> {
  try {
    const response = await fetch(`${BABYLOVEGROWTH_API_BASE}/${id}`, {
      headers: {
        "X-API-Key": apiKey,
        "Content-Type": "application/json",
      },
    });

    if (!response.ok) {
      console.error(`Failed to fetch article ${id}: ${response.status}`);
      return null;
    }

    return await response.json();
  } catch (error) {
    console.error(`Error fetching article ${id}:`, error);
    return null;
  }
}

Deno.serve(async (req) => {
  // Handle CORS
  const corsResponse = handleCors(req);
  if (corsResponse) return corsResponse;

  try {
    // Get API key from secrets
    const apiKey = Deno.env.get("BABYLOVEGROWTH_API_KEY");
    if (!apiKey) {
      return errorResponse("BabyLoveGrowth API key not configured. Please add BABYLOVEGROWTH_API_KEY secret.", 500);
    }

    // Create Supabase client with service role
    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const supabase = createClient(supabaseUrl, supabaseServiceKey);

    // Get last sync timestamp
    const { data: lastSyncData } = await supabase
      .from("integration_sync_log")
      .select("last_sync_at")
      .eq("integration_name", "babylovegrowth")
      .eq("status", "success")
      .order("last_sync_at", { ascending: false })
      .limit(1)
      .maybeSingle();

    const lastSyncAt = lastSyncData?.last_sync_at 
      ? new Date(lastSyncData.last_sync_at) 
      : new Date(0);

    console.log(`Last sync: ${lastSyncAt.toISOString()}`);

    // Fetch article list from BabyLoveGrowth API with pagination
    let allListItems: BabyLoveGrowthListItem[] = [];
    let page = 1;
    const limit = 50;
    let hasMore = true;

    while (hasMore) {
      const url = `${BABYLOVEGROWTH_API_BASE}?limit=${limit}&page=${page}`;
      console.log(`Fetching page ${page}: ${url}`);

      const response = await fetch(url, {
        headers: {
          "X-API-Key": apiKey,
          "Content-Type": "application/json",
        },
      });

      if (!response.ok) {
        const errorText = await response.text();
        console.error(`BabyLoveGrowth API error: ${response.status} - ${errorText}`);
        
        await supabase.from("integration_sync_log").insert({
          integration_name: "babylovegrowth",
          articles_imported: 0,
          status: "error",
          error_message: `API error: ${response.status} - ${errorText}`,
        });

        return errorResponse(`BabyLoveGrowth API error: ${response.status}`, 502);
      }

      const items: BabyLoveGrowthListItem[] = await response.json();
      
      if (items.length === 0) {
        hasMore = false;
      } else {
        allListItems = [...allListItems, ...items];
        
        if (items.length < limit) {
          hasMore = false;
        } else {
          page++;
        }
      }

      // Safety limit
      if (page > 100) {
        console.warn("Reached max pagination limit (100 pages)");
        hasMore = false;
      }
    }

    console.log(`Fetched ${allListItems.length} total articles from list`);

    // Get existing external_ids to filter out already imported
    const { data: existingPosts } = await supabase
      .from("blog_posts")
      .select("external_id")
      .eq("external_source", "babylovegrowth");

    const existingIds = new Set((existingPosts || []).map(p => p.external_id));

    // Filter to only new articles (not already imported)
    const newItems = allListItems.filter((item) => !existingIds.has(String(item.id)));

    console.log(`Found ${newItems.length} new articles available to import`);

    // Only import up to ARTICLES_PER_SYNC (1 per day for drip-feed)
    const itemsToImport = newItems.slice(0, ARTICLES_PER_SYNC);
    console.log(`Will import ${itemsToImport.length} article(s) this sync`);

    let importedCount = 0;
    const errors: string[] = [];

    // Fetch full details for each article to import
    for (const item of itemsToImport) {
      try {
        // Check if already imported
        const { data: existing } = await supabase
          .from("blog_posts")
          .select("id")
          .eq("external_id", String(item.id))
          .maybeSingle();

        if (existing) {
          console.log(`Article ${item.id} already exists, skipping`);
          continue;
        }

        // Fetch full article details by ID
        console.log(`Fetching full details for article ${item.id}`);
        const fullArticle = await fetchArticleById(item.id, apiKey);

        if (!fullArticle) {
          errors.push(`Article ${item.id}: Failed to fetch full details`);
          continue;
        }

        // Get content - try multiple field names
        const contentHtml = fullArticle.content_html || "";
        
        if (!contentHtml) {
          console.warn(`Article ${item.id} has no content_html`);
          errors.push(`Article ${item.id}: No content available`);
          continue;
        }

        const metaDesc = fullArticle.meta_description || item.metaDescription || "";
        const excerpt = metaDesc || extractExcerpt(contentHtml);
        const slug = fullArticle.slug || generateSlug(fullArticle.title || item.title);

        const blogPost = {
          external_id: String(item.id),
          external_source: "babylovegrowth",
          title: fullArticle.title || item.title,
          slug: slug,
          content: removeAttributionFooter(contentHtml),
          excerpt: excerpt,
          meta_title: fullArticle.title || item.title,
          meta_description: metaDesc,
          featured_image: fullArticle.hero_image_url || null,
          keywords: fullArticle.keywords || [],
          category: fullArticle.seedKeyword || "Health & Wellness",
          author: "Amir Wanas",
          is_published: true,
          published_at: new Date().toISOString(),
          reading_time_minutes: calculateReadingTime(contentHtml),
        };

        const { error } = await supabase
          .from("blog_posts")
          .upsert(blogPost, { 
            onConflict: "external_id",
            ignoreDuplicates: false 
          });

        if (error) {
          console.error(`Error importing article ${item.id}:`, error);
          errors.push(`Article ${item.id}: ${error.message}`);
        } else {
          importedCount++;
          console.log(`Imported article: ${blogPost.title}`);
        }
      } catch (err) {
        console.error(`Exception importing article ${item.id}:`, err);
        errors.push(`Article ${item.id}: ${err.message}`);
      }
    }

    // Log sync result
    await supabase.from("integration_sync_log").insert({
      integration_name: "babylovegrowth",
      articles_imported: importedCount,
      status: errors.length > 0 && importedCount === 0 ? "error" : errors.length > 0 ? "partial" : "success",
      error_message: errors.length > 0 ? errors.join("; ") : null,
    });

    console.log(`Sync complete: imported ${importedCount} articles`);

    return jsonResponse({
      success: true,
      imported: importedCount,
      total_fetched: allListItems.length,
      new_articles: newItems.length,
      errors: errors.length > 0 ? errors : undefined,
    });

  } catch (error) {
    console.error("Sync error:", error);

    try {
      const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
      const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
      const supabase = createClient(supabaseUrl, supabaseServiceKey);
      
      await supabase.from("integration_sync_log").insert({
        integration_name: "babylovegrowth",
        articles_imported: 0,
        status: "error",
        error_message: error.message,
      });
    } catch (logError) {
      console.error("Failed to log error:", logError);
    }

    return errorResponse(error.message, 500);
  }
});
