import { DocsLayout } from "@/components/docs/DocsLayout";
import { DocStep, DocTip, DocWarning, DocInfo } from "@/components/docs/DocComponents";
import { Package, BarChart3, TrendingUp, DollarSign, Users, PieChart } from "lucide-react";

export default function CoachPackageAnalyticsDocs() {
  return (
    <DocsLayout
      title="Package Analytics"
      description="Track session package performance, usage patterns, and revenue to optimise your service offerings."
      breadcrumbs={[
        { label: "For Coaches", href: "/docs/coach" },
        { label: "Package Analytics" }
      ]}
    >
      {/* Who This Is For */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
          <Package className="h-6 w-6 text-primary" />
          Who This Is For
        </h2>
        <p className="text-muted-foreground">
          Coaches who sell session packages and want to understand which packages perform best, 
          track usage rates, and make data-driven decisions about pricing and package structures.
        </p>
      </section>

      {/* What This Feature Does */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4">What This Feature Does</h2>
        <p className="text-muted-foreground mb-4">
          Package Analytics provides detailed insights into your session packages, including 
          sales volume, session utilisation, revenue per package type, and client retention 
          metrics. Use these insights to refine your offerings and maximise revenue.
        </p>
        <div className="grid md:grid-cols-3 gap-4">
          <div className="p-4 rounded-lg border border-border bg-card">
            <BarChart3 className="h-5 w-5 text-primary mb-2" />
            <h3 className="font-medium mb-1">Sales Tracking</h3>
            <p className="text-sm text-muted-foreground">
              See how many of each package type you've sold over time.
            </p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-card">
            <TrendingUp className="h-5 w-5 text-primary mb-2" />
            <h3 className="font-medium mb-1">Usage Rates</h3>
            <p className="text-sm text-muted-foreground">
              Track how quickly clients use their purchased sessions.
            </p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-card">
            <DollarSign className="h-5 w-5 text-primary mb-2" />
            <h3 className="font-medium mb-1">Revenue Analysis</h3>
            <p className="text-sm text-muted-foreground">
              Compare revenue generated by different package types.
            </p>
          </div>
        </div>
      </section>

      {/* Why This Feature Exists */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4">Why This Feature Exists</h2>
        <p className="text-muted-foreground">
          Understanding which packages sell best and how clients use them helps you optimise 
          your pricing strategy. You might discover that smaller packages have higher margins, 
          or that larger packages improve client retention. Data-driven decisions lead to 
          better business outcomes.
        </p>
      </section>

      {/* Key Metrics */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
          <PieChart className="h-6 w-6 text-primary" />
          Key Metrics Explained
        </h2>
        <div className="space-y-3">
          <div className="p-4 rounded-lg border border-border bg-card/50">
            <h3 className="font-medium mb-1">Packages Sold</h3>
            <p className="text-sm text-muted-foreground">
              Total number of each package type purchased within the selected period.
            </p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-card/50">
            <h3 className="font-medium mb-1">Session Utilisation Rate</h3>
            <p className="text-sm text-muted-foreground">
              Percentage of purchased sessions that have been used. Low rates may indicate 
              clients are buying more than they can commit to.
            </p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-card/50">
            <h3 className="font-medium mb-1">Average Sessions Per Week</h3>
            <p className="text-sm text-muted-foreground">
              How frequently clients use sessions from their packages on average.
            </p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-card/50">
            <h3 className="font-medium mb-1">Revenue Per Package</h3>
            <p className="text-sm text-muted-foreground">
              Total revenue generated by each package type, helping identify your most 
              profitable offerings.
            </p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-card/50">
            <h3 className="font-medium mb-1">Renewal Rate</h3>
            <p className="text-sm text-muted-foreground">
              Percentage of clients who purchase another package after completing one.
            </p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-card/50">
            <h3 className="font-medium mb-1">Expiration Rate</h3>
            <p className="text-sm text-muted-foreground">
              Percentage of packages that expire with unused sessions.
            </p>
          </div>
        </div>
      </section>

      {/* How to Access */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4">How to Access Package Analytics</h2>
        <div className="space-y-4">
          <DocStep stepNumber={1} title="Navigate to Analytics">
            Go to your coach dashboard and select "Analytics" or "Financial Reports" from the sidebar.
          </DocStep>
          <DocStep stepNumber={2} title="Select Package Tab">
            Choose the "Packages" tab to view package-specific analytics.
          </DocStep>
          <DocStep stepNumber={3} title="Filter by Date Range">
            Use the date picker to analyse specific periods (e.g., last month, last quarter, year-to-date).
          </DocStep>
          <DocStep stepNumber={4} title="Export Data">
            Download reports as CSV or PDF for offline analysis or record-keeping.
          </DocStep>
        </div>
      </section>

      {/* Client Retention Insights */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4 flex items-center gap-2">
          <Users className="h-6 w-6 text-primary" />
          Client Retention Insights
        </h2>
        <DocInfo>
          Package analytics can reveal which package structures lead to better client retention. 
          Clients on larger packages often show higher commitment and renewal rates.
        </DocInfo>
        <p className="text-muted-foreground mt-4">
          The analytics dashboard shows:
        </p>
        <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-2">
          <li>Clients who have renewed vs those who didn't</li>
          <li>Average client lifetime value by package type</li>
          <li>Common drop-off points (e.g., after first package expires)</li>
          <li>Package completion rates by client demographics</li>
        </ul>
      </section>

      {/* Optimisation Tips */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4">Optimising Your Packages</h2>
        <div className="space-y-3">
          <div className="p-4 rounded-lg border border-border bg-card/50">
            <h3 className="font-medium mb-1">High Expiration Rate?</h3>
            <p className="text-sm text-muted-foreground">
              Consider offering packages with longer validity periods or fewer sessions. 
              Clients may be overcommitting.
            </p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-card/50">
            <h3 className="font-medium mb-1">Low Renewal Rate?</h3>
            <p className="text-sm text-muted-foreground">
              Review client feedback and consider adding incentives for renewals, such as 
              loyalty discounts or bonus sessions.
            </p>
          </div>
          <div className="p-4 rounded-lg border border-border bg-card/50">
            <h3 className="font-medium mb-1">One Package Dominates Sales?</h3>
            <p className="text-sm text-muted-foreground">
              Evaluate whether other packages are priced or structured competitively. 
              Consider retiring underperforming options.
            </p>
          </div>
        </div>
      </section>

      {/* Limitations */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4">Limitations & Important Notes</h2>
        <DocWarning>
          Analytics reflect data from bookings made through the platform only. Sessions booked 
          externally are not tracked unless manually logged.
        </DocWarning>
        <ul className="list-disc list-inside text-muted-foreground space-y-2 mt-4">
          <li>Historical data is available from the date you started using packages</li>
          <li>Refunded packages are excluded from revenue calculations</li>
          <li>Expired unused sessions are tracked separately from used sessions</li>
        </ul>
      </section>

      {/* FAQs */}
      <section className="mb-10">
        <h2 className="text-2xl font-semibold mb-4">FAQs</h2>
        <div className="space-y-4">
          <div>
            <h3 className="font-medium mb-1">Can I see which specific clients bought which packages?</h3>
            <p className="text-sm text-muted-foreground">
              Yes, you can drill down from the analytics overview to see individual client 
              purchase history for each package type.
            </p>
          </div>
          <div>
            <h3 className="font-medium mb-1">How often is the data updated?</h3>
            <p className="text-sm text-muted-foreground">
              Analytics are updated in real-time as bookings are made, sessions are completed, 
              and packages are purchased.
            </p>
          </div>
          <div>
            <h3 className="font-medium mb-1">Can I compare different time periods?</h3>
            <p className="text-sm text-muted-foreground">
              Yes, you can select two date ranges to compare performance side-by-side, such 
              as this quarter vs last quarter.
            </p>
          </div>
          <div>
            <h3 className="font-medium mb-1">Are subscription clients included in package analytics?</h3>
            <p className="text-sm text-muted-foreground">
              No, subscriptions have their own analytics section. Package analytics focus 
              specifically on session packages with defined session counts.
            </p>
          </div>
        </div>
      </section>

      <DocTip>
        Review package analytics monthly to identify trends early. Small adjustments to 
        pricing or package structure can significantly impact your bottom line over time.
      </DocTip>
    </DocsLayout>
  );
}
